// npm run gen-abi    rewrites src/generated/giftVaultAbi.ts from the Foundry build of GiftVault
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ARTIFACT = new URL("../../contracts/out/GiftVault.sol/GiftVault.json", import.meta.url);
const OUTPUT = new URL("../src/generated/giftVaultAbi.ts", import.meta.url);

// The server encodes claim and createGift calldata and decodes GiftClaimed logs from this ABI, and
// gift.ts signs key proofs only a vault with registerDigest and BadKeyProof checks (C32), so an
// artifact that lacks any of these is the wrong file, not a smaller vault.
const REQUIRED = [
  "function:claim",
  "function:createGift",
  "function:getGift",
  "function:registerDigest",
  "event:GiftClaimed",
  "error:GiftNotOpen",
  "error:BadKeyProof",
];

function stop(message: string): never {
  console.error(`gen-abi: ${message}`);
  process.exit(1);
}

if (!existsSync(ARTIFACT)) {
  stop(`${fileURLToPath(ARTIFACT)} is missing. Build the contracts first (forge build in packages/contracts).`);
}

let artifact: unknown;
try {
  artifact = JSON.parse(readFileSync(ARTIFACT, "utf8"));
} catch {
  stop("the GiftVault artifact is not valid JSON.");
}

const abi = (artifact as { abi?: unknown } | null)?.abi;
if (!Array.isArray(abi) || abi.length === 0) stop("the GiftVault artifact has no ABI.");

const present = new Set(
  abi.map((item: unknown) => {
    const entry = item as { type?: unknown; name?: unknown };
    return `${String(entry.type)}:${String(entry.name)}`;
  }),
);
const missing = REQUIRED.filter((r) => !present.has(r));
if (missing.length > 0) stop(`the GiftVault ABI lacks ${missing.join(", ")}.`);

const source = [
  "// Generated by scripts/gen-abi.ts from packages/contracts/out/GiftVault.sol/GiftVault.json.",
  "// Do not edit by hand: rebuild the contracts, then run npm run gen-abi.",
  `export const giftVaultAbi = ${JSON.stringify(abi, null, 2)} as const;`,
  "",
].join("\n");

mkdirSync(new URL(".", OUTPUT), { recursive: true });
writeFileSync(OUTPUT, source, "utf8");
console.log(`gen-abi: wrote ${abi.length} ABI entries to ${fileURLToPath(OUTPUT)}`);
